server:
  port: 7002

spring:
  application:
    name: socket_pjt
  datasource:
    url: jdbc:mysql://localhost:3306/spring_chatting
    username: root
    password: ssafy12!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

token:
  secret-key: "SECRET"
  refresh-secret-key: "REFRESH_SECRET"
  token-time: 300
  refresh-token-time: 300

springdoc:
  swagger-ui:
    csrf:
      enabled: true
      operations-sorter: method
